apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: invoice-management
  namespace: invoice-management

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - cluster-issuer.yaml

namespace: invoice-management

images:
  - name: ghcr.io/rxtech-lab/invoice-management
    newTag: latest
